### ISSUE TITLE
A nice repo for 3D generation!

### ISSUE THREAD

**Issue by YuDeng** [justimyhxu/awesome-3D-generation#5]
Accidentally saw this repo. A really nice one to help gain a comprehensive understanding of the 3D generation field!

Here are some latest 3D-aware gan papers that could be potentially added to this repo:
GRAM-HD: 3D-Consistent Image Generation at High Resolution with Generative Radiance Manifolds (https://arxiv.org/abs/2206.07255)
VoxGRAF: Fast 3D-Aware Image Synthesis with Sparse Voxel Grids (https://arxiv.org/abs/2206.07695)
EpiGRAF: Rethinking training of 3D GANs (https://arxiv.org/abs/2206.10535)

**Comment by pengsida** [comment]
Cool! We have added these papers. Thank you!
